### ISSUE TITLE
[BUG][Vision] weird range for non-outliers in only positive parameters

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1336]
**Describe the bug**
When calculating range for non outlier (for example in label property outliers - bbox size) the range contains negative numbers, which seems bad on the eye since the field can only contain positive values 

**To Reproduce**
see following notebook - https://www.kaggle.com/nadavbarak/car-licence-plate-resnet50-deepchecks

**Expected behavior**
cut the lower bound for non outliers at 0 for cases like this

**Screenshots**
![Screen Shot 2022-04-27 at 10 54 48](https://user-images.githubusercontent.com/67195469/165471072-8190fbff-0c25-4b99-909d-9bee168bc30c.png)

**Comment by matanper** [comment]
we already fixed that, did you run on latest?

**Comment by Nadav-Barak** [comment]
Run the notebook again with the version currently at main, the behaviour is repeated (bug still there)

**Comment by noamzbr** [comment]
Desired behavior - the range can't be more than (min, max)
Could be bug in bbox area calculation?

**Comment by Nadav-Barak** [comment]
The problem was in my implementation of batch to labels (got negative hight). Additing relevant conditions to validate_format
