### ISSUE TITLE
[BUG] Default Zoom displays in a problematic manner, when there are few close values

### ISSUE THREAD

**Issue by shir22** [deepchecks/deepchecks#1880]
**Describe the bug**
See here:
https://docs.deepchecks.com/0.7/checks_gallery/vision/train_test_validation/plot_image_property_drift.html#observe-the-checks-output 
Scrolling a bit down will show:
![CleanShot 2022-08-04 at 17 42 54](https://user-images.githubusercontent.com/33841818/182875873-eb29b1b8-8a80-4747-9b83-73fba22df8f4.png)
Instead of something like this (when double clicking):
![CleanShot 2022-08-04 at 17 43 03](https://user-images.githubusercontent.com/33841818/182875927-dcf3a048-b28f-411d-b12a-9839e7779005.png)

@matanper - I guess this relates to some of zoom default changes you did for nice categorical plots? (can we find a way in the middle so that both categorical and these types of plots will look reasonable)

**Comment by matanper** [comment]
I think Yurii was the last one to change the default range logic

**Comment by Nadav-Barak** [comment]
Play around with the plotly parameters and try and fix this

**Comment by shir22** [comment]
Following our oral discussion, note two topics in this bug:
1. Is there another bug -> numerical identified as categorical? Do we (and should we?) have a logic of float that should be identified as numerical and not categorical?
2. Display-wise bug -> there is some logic that was added to bar-charts so that the bars won't be too wide (when there are only a few bars), consult with @matanper if adapting of changing any plotly configurations

**Comment by nirhutnik** [comment]
This was already fixed in 0.8. 
In the 0.8 docs everything is fine - https://docs.deepchecks.com/0.8/checks_gallery/vision/train_test_validation/plot_image_property_drift.html#observe-the-checks-output

**Comment by shir22** [comment]
Bug still exists as is... (in documentation example the "classes to display" were changed, but if you run it with the original code cell (that can be taken from the 0.7 documentation in the example above):
`check_result = ImagePropertyDrift(classes_to_display=['bicycle', 'bench', 'bus', 'truck'], min_samples=5
                                  ).run(train_dataset, test_dataset)
check_result.show()`

Bug still exists:
![CleanShot 2022-09-11 at 16 04 03](https://user-images.githubusercontent.com/33841818/189529057-645e4be6-80f2-4710-8df4-8c4e8d9ae178.png)

**Comment by noamzbr** [comment]
The only bug that remains to be solved here is the fact that the default zoom "squeezes" the whole range into the center of the plot for some cases. This is a edge-case bug, as we only got it here because min_samples=5 was set manually.
